version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - db
      - redis
      - mongo
    volumes:
      - ./logs:/app/logs

  worker:
    build: .
    command: celery -A reminder_service worker --loglevel=info
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - db
      - redis
      - mongo
    volumes:
      - ./logs:/app/logs

  beat:
    build: .
    command: celery -A reminder_service beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - db
      - redis
      - mongo
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=reminder_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_DATABASE=smartqueue
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
